"use client";

import { useState } from "react";
import { buildConsistencyProfile, projectFormBands, pointsToNextTier, consistencyNote, FormDiagnosis, type FormPoint } from "@/lib/consistency";
import { EventProfile, Verdict } from "@/lib/event-selector";
import { draftOdds, type DraftOdds, type DraftBasis } from "@/lib/draft-odds";
import { TrendingUp, Radar, Info, ArrowRight } from "lucide-react";
import clsx from "clsx";
import { useTranslations } from "next-intl";

/**
 * Consistency tracker — the "growth vs volatility" decomposition
 * (lib/consistency.ts) plus its translation into alliance outcomes at real
 * event fields.
 *
 * Team-agnostic: it renders whatever chronological series it is handed. The
 * curated 30311 retrospective feeds it hand-verified FTCScout OPRs
 * (TeamSeasonReport); every other team gets the same view built live from the
 * FIRST API (TeamSeasonAnalysis → lib/team-season-analysis.ts).
 *
 * Client component only because of the event picker; all the math is pure.
 *
 * The six fields below are copied from lib/data/event-profiles.json (2025
 * season, generated by scripts/oracle-backtest.mjs export-profiles). They are
 * inlined rather than imported so the team page doesn't ship all 1,213
 * profiles — the full picker already exists in /analytics → Selector de
 * eventos. Curation: their own Premier, the two reachable Premiers from
 * decisions.md #58, the hardest one, a Worlds division, and their national
 * championship.
 */
const FIELDS: EventProfile[] = [
    { season: 2025, code: "FPEMX", name: "México Premier Event", type: "Premier", region: "FPE", teams: 29, oprMean: 56.6, oprSd: 32.6, oprTop: 139.1, sigma: 33.2 },
    { season: 2025, code: "MXCMP", name: "Mexico Championship", type: "Championship", region: "MX", teams: 52, oprMean: 57.1, oprSd: 24.5, oprTop: 126.8, sigma: 27.9 },
    { season: 2025, code: "FPERRMOW", name: "Run for the Robots — Man o' War", type: "Premier", region: "FPE", teams: 36, oprMean: 69.4, oprSd: 39.8, oprTop: 178.9, sigma: 35 },
    { season: 2025, code: "FPENE1", name: "New England — Martin", type: "Premier", region: "FPE", teams: 27, oprMean: 72.1, oprSd: 31.8, oprTop: 144.4, sigma: 36.9 },
    { season: 2025, code: "FPEWESEA", name: "Western Edge — Sea", type: "Premier", region: "FPE", teams: 44, oprMean: 88.9, oprSd: 45.2, oprTop: 198.2, sigma: 51.8 },
    { season: 2025, code: "FTCCMP1FRAN", name: "Mundial — División Franklin", type: "FIRSTChampionship", region: "CMPZ2", teams: 57, oprMean: 109, oprSd: 43.1, oprTop: 203.1, sigma: 50.8 },
];

// Style-only maps — labels come from next-intl (Consistency.diagnosisLabel /
// EventSelector.verdict), keyed by the semantic enums lib/consistency.ts and
// lib/event-selector.ts return. See docs/architecture/i18n.md.
const DIAGNOSIS_STYLE: Record<FormDiagnosis, { cls: string }> = {
    crecimiento: { cls: "text-success bg-success/10 border-success/25" },
    declive: { cls: "text-danger bg-danger/10 border-danger/25" },
    volatilidad: { cls: "text-warning bg-warning/10 border-warning/25" },
    mixto: { cls: "text-warning bg-warning/10 border-warning/25" },
    estable: { cls: "text-secondary bg-secondary/10 border-secondary/25" },
    insuficiente: { cls: "text-muted-foreground bg-muted border-border" },
};

const VERDICT_STYLE: Record<Verdict, { cls: string }> = {
    capitan: { cls: "text-primary bg-primary/10 border-primary/25" },
    pick: { cls: "text-success bg-success/10 border-success/25" },
    burbuja: { cls: "text-warning bg-warning/10 border-warning/25" },
    fuera: { cls: "text-muted-foreground bg-muted border-border" },
};

export interface ConsistencyTrackerProps {
    /** Chronological form series — one point per event, oldest first. */
    points: FormPoint[];
    /** The season-blended number other teams scout this one on. */
    publicNumber: number;
    /**
     * Renders the FTCScout-vs-internal methodology caveat. Only true for the
     * curated report, whose series comes from FTCScout's OPR; the live series
     * is built by us end to end and carries its own note instead.
     */
    showFtcScoutCaveat?: boolean;
}

export function ConsistencyTracker({ points, publicNumber, showFtcScoutCaveat }: ConsistencyTrackerProps) {
    const [fieldCode, setFieldCode] = useState(FIELDS[0].code);
    const tOdds = useTranslations("DraftOdds");
    const tConsistency = useTranslations("Consistency");
    const tSelector = useTranslations("EventSelector");
    // draftOdds returns a translation key + params (never prose); render it here.
    const basisText = (basis: DraftBasis) => {
        const { key, ...params } = basis;
        return tOdds(key, params);
    };
    // consistencyNote returns a translation key + params too (lib/consistency.ts).
    const noteText = (note: ReturnType<typeof consistencyNote>) => {
        const { key, ...params } = note;
        return tConsistency(`note.${key}`, params);
    };
    const diagnosisLabel = (d: FormDiagnosis) => tConsistency(`diagnosisLabel.${d}`);
    const verdictLabel = (v: Verdict) => tSelector(`verdict.${v}`);
    const phaseLabel = (key: string) => tConsistency(`phase.${key}`);
    const bandLabel = (key: string) => tConsistency(`band.${key}.label`);
    const bandHint = (key: string) => tConsistency(`band.${key}.hint`);

    const profile = buildConsistencyProfile(points, publicNumber);

    const field = FIELDS.find(f => f.code === fieldCode) ?? FIELDS[0];
    const bands = projectFormBands(profile, field);
    const nextTier = pointsToNextTier(profile.publicNumber, field);
    const growthPct = profile.tot.r2 * 100;
    // Signed here rather than in the catalog: a hardcoded "+" would print
    // "+-3.0" on a declining season.
    const slopeText = signed(profile.tot.slope);

    return (
        <div className="space-y-5">
            {/* ── Headline diagnosis ─────────────────────────────────────── */}
            <div className="rounded-2xl border border-border bg-card p-5 md:p-6">
                <div className="flex flex-wrap items-center gap-2 mb-4">
                    <span className={clsx("text-[10px] font-black uppercase tracking-wider px-2.5 py-1 rounded-full border", DIAGNOSIS_STYLE[profile.diagnosis].cls)}>
                        {diagnosisLabel(profile.diagnosis)}
                    </span>
                    <span className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">
                        {tConsistency("ui.eventsAnalyzed", { n: profile.tot.n })}
                    </span>
                </div>

                <p className="text-foreground leading-relaxed md:text-lg text-balance">
                    {noteText(consistencyNote(profile))}
                </p>

                <div className="mt-6 grid grid-cols-2 lg:grid-cols-4 gap-3">
                    <Metric
                        value={`${growthPct.toFixed(0)}%`}
                        label={tConsistency("ui.metric.trendShare.label")}
                        sub={tConsistency("ui.metric.trendShare.sub", { slope: slopeText })}
                        tone="success"
                    />
                    <Metric
                        value={`±${profile.tot.residualSigma.toFixed(1)}`}
                        label={tConsistency("ui.metric.volatility.label")}
                        sub={tConsistency("ui.metric.volatility.sub", { rawSigma: profile.tot.rawSigma.toFixed(1) })}
                        tone="warning"
                    />
                    <Metric
                        value={`${profile.scoutingGap > 0 ? "−" : "+"}${Math.abs(profile.scoutingGap).toFixed(1)}`}
                        label={tConsistency("ui.metric.scoutingGap.label")}
                        sub={tConsistency("ui.metric.scoutingGap.sub")}
                        tone="danger"
                    />
                    <Metric
                        value={`${(profile.realizationRate * 100).toFixed(0)}%`}
                        label={tConsistency("ui.metric.realization.label")}
                        sub={tConsistency("ui.metric.realization.sub", {
                            publicNumber: profile.publicNumber.toFixed(1),
                            peak: profile.tot.max.toFixed(1),
                        })}
                        tone="secondary"
                    />
                </div>
            </div>

            {/* ── Trend vs noise chart ───────────────────────────────────── */}
            <TrendChart profile={profile} points={points} />

            {/* ── Phase decomposition ────────────────────────────────────── */}
            {profile.phases.length > 0 && (
                <div className="rounded-2xl border border-border bg-card p-5 md:p-6">
                    <h4 className="font-display font-black text-foreground flex items-center gap-2 mb-1">
                        <Radar size={17} className="text-secondary" /> {tConsistency("ui.phases.title")}
                    </h4>
                    <p className="text-sm text-muted-foreground mb-4 max-w-2xl">
                        {tConsistency.rich("ui.phases.desc", { em: chunks => <em>{chunks}</em> })}
                    </p>

                    <div className="grid sm:grid-cols-2 gap-3">
                        {profile.phases.map(ph => {
                            const isDriver = profile.volatilityDriver?.key === ph.key;
                            return (
                                <div key={ph.key} className={clsx("rounded-xl border p-4", isDriver ? "border-warning/40 bg-warning/5" : "border-border bg-muted/30")}>
                                    <div className="flex items-center justify-between gap-2 mb-3">
                                        <span className="font-bold text-foreground">{phaseLabel(ph.key)}</span>
                                        <span className={clsx("text-[10px] font-black uppercase tracking-wider px-2 py-0.5 rounded-full border", DIAGNOSIS_STYLE[ph.diagnosis].cls)}>
                                            {diagnosisLabel(ph.diagnosis)}
                                        </span>
                                    </div>
                                    <dl className="grid grid-cols-3 gap-2 text-center">
                                        <Stat label={tConsistency("ui.stat.trend")} value={signed(ph.analysis.slope)} />
                                        <Stat label={tConsistency("ui.stat.explained")} value={`${(ph.analysis.r2 * 100).toFixed(0)}%`} />
                                        <Stat label={tConsistency("ui.stat.noise")} value={`±${ph.analysis.residualSigma.toFixed(1)}`} />
                                    </dl>
                                    {isDriver && (
                                        <p className="mt-3 text-xs text-warning font-semibold flex items-start gap-1.5">
                                            <Info size={13} className="shrink-0 mt-0.5" />
                                            {tConsistency("ui.phases.driver")}
                                        </p>
                                    )}
                                </div>
                            );
                        })}
                    </div>
                </div>
            )}

            {/* ── Translation into alliance outcomes ─────────────────────── */}
            <div className="rounded-2xl border border-border bg-card p-5 md:p-6">
                <div className="flex flex-wrap items-start justify-between gap-4 mb-4">
                    <div>
                        <h4 className="font-display font-black text-foreground flex items-center gap-2 mb-1">
                            <TrendingUp size={17} className="text-primary" /> {tConsistency("ui.bands.title")}
                        </h4>
                        <p className="text-sm text-muted-foreground max-w-2xl">
                            {tConsistency.rich("ui.bands.desc", { b: chunks => <strong className="text-foreground">{chunks}</strong> })}
                        </p>
                    </div>
                    <label className="shrink-0">
                        <span className="block text-[10px] font-bold uppercase tracking-wider text-muted-foreground mb-1">{tConsistency("ui.bands.fieldLabel")}</span>
                        <select
                            value={fieldCode}
                            onChange={e => setFieldCode(e.target.value)}
                            className="px-3 py-2 bg-muted border border-border rounded-lg text-sm text-foreground font-medium max-w-[16rem]"
                        >
                            {FIELDS.map(f => (
                                <option key={f.code} value={f.code}>{f.name} · {f.teams} eq.</option>
                            ))}
                        </select>
                    </label>
                </div>

                <div className="overflow-x-auto rounded-xl border border-border">
                    <table className="w-full min-w-[560px] text-sm">
                        <thead>
                            <tr className="bg-muted/50 text-muted-foreground text-[10px] uppercase tracking-widest">
                                <th className="px-4 py-3 text-left font-bold">{tConsistency("ui.table.form")}</th>
                                <th className="px-4 py-3 text-center font-bold">{tConsistency("ui.table.opr")}</th>
                                <th className="px-4 py-3 text-center font-bold">{tConsistency("ui.table.seed")}</th>
                                <th className="px-4 py-3 text-center font-bold">{tConsistency("ui.table.allianceProb")}</th>
                                <th className="px-4 py-3 text-center font-bold">{tConsistency("ui.table.outcome")}</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-border">
                            {bands.map(b => (
                                <tr key={b.key} className={clsx(b.key === "publico" && "bg-danger/5", b.key === "actual" && "bg-success/5")}>
                                    <td className="px-4 py-3">
                                        <div className="font-bold text-foreground">{bandLabel(b.key)}</div>
                                        <div className="text-xs text-muted-foreground">{bandHint(b.key)}</div>
                                    </td>
                                    <td className="px-4 py-3 text-center font-mono font-bold text-secondary tabular-nums">{b.opr.toFixed(1)}</td>
                                    <td className="px-4 py-3 text-center font-mono text-foreground tabular-nums whitespace-nowrap">
                                        #{b.projection.expectedSeed}<span className="text-muted-foreground text-xs">/{field.teams}</span>
                                    </td>
                                    {/* Measured selection rate at that seed (606 events), rather than
                                        the verdict's eyeballed thresholds — "burbuja" reads the same
                                        at 45% and 85%, and those plan very differently. */}
                                    <td className="px-4 py-3 text-center font-mono tabular-nums" title={basisText(draftOdds(b.projection.expectedSeed, b.projection.alliances, b.projection.percentile).basis)}>
                                        <PickOdds
                                            odds={draftOdds(b.projection.expectedSeed, b.projection.alliances, b.projection.percentile)}
                                        />
                                    </td>
                                    <td className="px-4 py-3 text-center">
                                        <span className={clsx("inline-block px-2.5 py-1 rounded-full text-[10px] font-black uppercase tracking-wider border whitespace-nowrap", VERDICT_STYLE[b.projection.verdict].cls)}>
                                            {verdictLabel(b.projection.verdict)}
                                        </span>
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>

                {nextTier && (
                    <p className="mt-4 text-sm text-foreground bg-primary/5 border border-primary/20 rounded-xl px-4 py-3 flex items-start gap-2.5">
                        <ArrowRight size={16} className="text-primary shrink-0 mt-0.5" />
                        <span>
                            {tConsistency.rich(nextTier.delta > 0 ? "ui.nextTier.gap" : "ui.nextTier.reached", {
                                from: verdictLabel(nextTier.from).toLowerCase(),
                                to: verdictLabel(nextTier.to).toLowerCase(),
                                opr: nextTier.oprNeeded.toFixed(1),
                                delta: nextTier.delta.toFixed(1),
                                b: chunks => <strong>{chunks}</strong>,
                                m: chunks => <strong className="font-mono">{chunks}</strong>,
                                hi: chunks => <strong className="font-mono text-primary">{chunks}</strong>,
                            })}
                        </span>
                    </p>
                )}

                <p className="mt-3 text-[11px] text-muted-foreground flex items-start gap-1.5 leading-snug">
                    <Info size={12} className="shrink-0 mt-0.5" />
                    <span>
                        {tConsistency("ui.footnote.directional")}
                        {showFtcScoutCaveat && ` ${tConsistency("ui.footnote.ftcScout")}`}
                    </span>
                </p>
            </div>
        </div>
    );
}

/**
 * Season series with its fitted trend and a ±residual band. The visual makes
 * the module's whole point legible at a glance: the dots track the line
 * (growth), and the public number sits well below where the line ends (lag).
 */
function TrendChart({ profile, points }: { profile: ReturnType<typeof buildConsistencyProfile>; points: FormPoint[] }) {
    const t = useTranslations("Consistency");
    const values = points.map(p => p.opr);
    const { slope, currentForm, residualSigma, n } = profile.tot;
    // x(i) divides by n-1, and a single point has no trend to draw anyway.
    // Callers are expected to filter this out upstream; this is the backstop.
    if (n < 2) return null;
    const intercept = currentForm - slope * (n - 1);
    const fit = (i: number) => intercept + slope * i;

    const W = 720, H = 280, padX = 46, padY = 30;
    const lo = Math.min(...values, fit(0) - residualSigma, profile.publicNumber);
    const hi = Math.max(...values, fit(n - 1) + residualSigma);

    // Snap the axis to a round step so the labels read 40/50/60… instead of
    // 40/52.5/65…. Smallest step that keeps the axis under ~6 gridlines.
    const span = hi - lo || 10;
    const pad = span * 0.1;
    const step = [5, 10, 20, 25, 50, 100].find(s => span / s <= 6) ?? 200;
    const min = Math.floor((lo - pad) / step) * step;
    const max = Math.ceil((hi + pad) / step) * step;

    const x = (i: number) => padX + (i * (W - padX * 2)) / (n - 1);
    const y = (v: number) => padY + (H - padY * 2) * (1 - (v - min) / (max - min));

    const grid = Array.from({ length: Math.round((max - min) / step) + 1 }, (_, k) => min + k * step);

    const bandPath = [
        `M${x(0)},${y(fit(0) + residualSigma)}`,
        `L${x(n - 1)},${y(fit(n - 1) + residualSigma)}`,
        `L${x(n - 1)},${y(fit(n - 1) - residualSigma)}`,
        `L${x(0)},${y(fit(0) - residualSigma)}`,
        "Z",
    ].join(" ");

    return (
        <div className="rounded-2xl border border-border bg-card p-4 md:p-6">
            <svg viewBox={`0 0 ${W} ${H}`} className="w-full h-auto" role="img"
                aria-label={t("ui.chart.aria", {
                    slope: signed(slope),
                    r2Pct: (profile.tot.r2 * 100).toFixed(0),
                    publicNumber: profile.publicNumber.toFixed(1),
                    currentForm: currentForm.toFixed(1),
                })}>
                {grid.map(g => (
                    <g key={g}>
                        <line x1={padX} x2={W - padX} y1={y(g)} y2={y(g)} stroke="var(--color-border)" strokeWidth="1" />
                        <text x={padX - 10} y={y(g) + 4} textAnchor="end" className="fill-[var(--color-muted-foreground)]" fontSize="11" fontFamily="var(--font-mono)">{g.toFixed(0)}</text>
                    </g>
                ))}

                {/* residual band — the volatility the trend does not explain */}
                <path d={bandPath} fill="var(--color-success)" fillOpacity="0.10" />

                {/* fitted trend */}
                <line x1={x(0)} y1={y(fit(0))} x2={x(n - 1)} y2={y(fit(n - 1))}
                    stroke="var(--color-success)" strokeWidth="2.5" strokeDasharray="7 5" strokeLinecap="round" />

                {/* the public season number — what captains actually scout on */}
                <line x1={padX} x2={W - padX} y1={y(profile.publicNumber)} y2={y(profile.publicNumber)}
                    stroke="var(--color-danger)" strokeWidth="2" strokeDasharray="3 4" />
                <text x={W - padX} y={y(profile.publicNumber) - 8} textAnchor="end"
                    className="fill-[var(--color-danger)]" fontSize="11" fontWeight="800" fontFamily="var(--font-mono)">
                    {t("ui.chart.publicNumberTag", { value: profile.publicNumber.toFixed(1) })}
                </text>

                {/* observed events */}
                <path d={values.map((v, i) => `${i === 0 ? "M" : "L"}${x(i)},${y(v)}`).join(" ")}
                    fill="none" stroke="var(--color-primary)" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" />
                {values.map((v, i) => (
                    <g key={`${points[i].label}-${i}`}>
                        <circle cx={x(i)} cy={y(v)} r="6" fill="var(--color-card)" stroke="var(--color-primary)" strokeWidth="3" />
                        <text x={x(i)} y={y(v) - 15} textAnchor="middle" className="fill-[var(--color-foreground)]" fontSize="14" fontWeight="800" fontFamily="var(--font-display)">{v.toFixed(1)}</text>
                        <text x={x(i)} y={H - padY + 20} textAnchor="middle" className="fill-[var(--color-muted-foreground)]" fontSize="12" fontWeight="700" fontFamily="var(--font-mono)">{points[i].label}</text>
                    </g>
                ))}
            </svg>

            <div className="mt-3 flex flex-wrap items-center gap-x-5 gap-y-2 text-xs text-muted-foreground px-1">
                <LegendKey color="var(--color-primary)" label={t("ui.chart.legend.observed")} />
                <LegendKey color="var(--color-success)" label={t("ui.chart.legend.trend", { slope: signed(slope) })} dashed />
                <LegendKey color="var(--color-success)" label={t("ui.chart.legend.band", { sigma: residualSigma.toFixed(1) })} band />
                <LegendKey color="var(--color-danger)" label={t("ui.chart.legend.publicNumber")} dashed />
            </div>
        </div>
    );
}

function LegendKey({ color, label, dashed, band }: { color: string; label: string; dashed?: boolean; band?: boolean }) {
    return (
        <span className="flex items-center gap-1.5">
            <span
                aria-hidden
                className={clsx("inline-block rounded-full", band ? "w-3.5 h-3.5" : "w-4 h-0.5")}
                style={band
                    ? { backgroundColor: color, opacity: 0.25 }
                    : { backgroundImage: dashed ? `repeating-linear-gradient(90deg, ${color} 0 4px, transparent 4px 7px)` : "none", backgroundColor: dashed ? "transparent" : color }}
            />
            {label}
        </span>
    );
}

/**
 * Selection probability with its OPR adjustment shown, because the adjustment
 * IS the actionable part: at the same seed, being visibly good is worth more
 * than a couple of ranking positions (decisions.md #72).
 */
function PickOdds({ odds }: { odds: DraftOdds }) {
    const t = useTranslations("Consistency");
    const p = odds.probability;
    const tone = p >= 0.85 ? "text-success" : p >= 0.6 ? "text-warning" : "text-danger";
    return (
        <span className="inline-flex flex-col items-center leading-tight">
            <span className={clsx("font-bold", tone)}>{(p * 100).toFixed(0)}%</span>
            {Math.abs(odds.oprAdjustment) >= 0.02 && (
                <span className="text-[10px] font-normal text-muted-foreground mt-0.5">
                    {t("ui.oprAdjustment", { delta: signed(odds.oprAdjustment * 100, 0) })}
                </span>
            )}
        </span>
    );
}

/** Explicitly signed fixed-point number, so "+3.1" / "−3.1" never becomes "+-3.1". */
function signed(v: number, digits = 1): string {
    return `${v >= 0 ? "+" : ""}${v.toFixed(digits)}`;
}

function Metric({ value, label, sub, tone }: { value: string; label: string; sub: string; tone: "success" | "warning" | "danger" | "secondary" }) {
    const toneCls = {
        success: "text-success",
        warning: "text-warning",
        danger: "text-danger",
        secondary: "text-secondary",
    }[tone];

    return (
        <div className="rounded-xl border border-border bg-muted/30 p-4">
            <div className={clsx("font-display font-black text-2xl md:text-3xl tabular-nums", toneCls)}>{value}</div>
            <div className="text-xs font-bold text-foreground mt-1 leading-snug">{label}</div>
            <div className="text-[11px] text-muted-foreground mt-1 leading-snug">{sub}</div>
        </div>
    );
}

function Stat({ label, value }: { label: string; value: string }) {
    return (
        <div>
            <dd className="font-mono font-bold text-foreground tabular-nums">{value}</dd>
            <dt className="text-[10px] uppercase tracking-wider text-muted-foreground mt-0.5">{label}</dt>
        </div>
    );
}
