import type { AggregatedTeamStats, MatchScouting, PitScouting } from "@/types/scouting";
import {
    calculateTeamProjection,
    predictMatch,
    type MatchProjection,
    type TeamProjection,
} from "@/lib/projections";

/**
 * Briefing composition layer. Pure function — no Firestore, no React. Takes
 * the same inputs the MatchSimulator already has access to and produces a
 * single object the printable view can render without further computation.
 *
 * The output mirrors the structure the drive coach needs:
 *   - Match identity (number, alliances, event)
 *   - Score prediction with confidence
 *   - Per-team line items
 *   - Strategic insights (auto-generated from the projection)
 */

export interface BriefingTeamRow {
    teamNumber: number;
    teamName: string;
    projectedPoints: number;
    breakdownAuto: number;
    breakdownTeleop: number;
    breakdownEndgame: number;
    averageRS: number;
    averageNP: number;
    reliability: "high" | "medium" | "low";
    redFlags: string[];
    /** Most recent 2 notes from match scouting for this team. */
    recentNotes: string[];
}

export interface BriefingData {
    eventCode: string;
    season: number;
    matchNumber: number;

    redAlliance: {
        teams: BriefingTeamRow[];
        projectedScore: number;
    };
    blueAlliance: {
        teams: BriefingTeamRow[];
        projectedScore: number;
    };

    /** P(red wins), in [0, 1]. */
    winProbabilityRed: number;
    /** Insights generated by predictMatch (Spanish, ready to render). */
    insights: string[];
    /** Auto-derived strategic focus bullets specific to this match. */
    strategicFocus: string[];
    /** ISO timestamp of when the briefing was generated. */
    generatedAt: string;
    /** Which org generated the briefing (for the header). */
    orgId: string;
}

interface BuildBriefingOpts {
    matchNumber: number;
    eventCode: string;
    season: number;
    orgId: string;
    redTeamNumbers: number[];
    blueTeamNumbers: number[];
    teams: AggregatedTeamStats[];
    scoutingEntries: MatchScouting[];
    pitDataByTeam?: Record<number, PitScouting | null>;
}

export function buildBriefingData(opts: BuildBriefingOpts): BriefingData {
    const { teams, scoutingEntries, pitDataByTeam = {} } = opts;
    const teamByNumber = new Map(teams.map(t => [t.teamNumber, t]));

    const redProjections = opts.redTeamNumbers.map(n =>
        buildTeamProjection(n, teamByNumber, scoutingEntries, pitDataByTeam),
    );
    const blueProjections = opts.blueTeamNumbers.map(n =>
        buildTeamProjection(n, teamByNumber, scoutingEntries, pitDataByTeam),
    );

    const matchPrediction = predictMatch(
        redProjections.map(r => r.projection),
        blueProjections.map(b => b.projection),
    );

    return {
        eventCode: opts.eventCode,
        season: opts.season,
        matchNumber: opts.matchNumber,
        redAlliance: {
            teams: redProjections.map(r => r.row),
            projectedScore: matchPrediction.redAlliance.score,
        },
        blueAlliance: {
            teams: blueProjections.map(b => b.row),
            projectedScore: matchPrediction.blueAlliance.score,
        },
        winProbabilityRed: matchPrediction.winProbability,
        insights: matchPrediction.insights,
        strategicFocus: deriveStrategicFocus(matchPrediction, redProjections.map(r => r.row), blueProjections.map(b => b.row)),
        generatedAt: new Date().toISOString(),
        orgId: opts.orgId,
    };
}

function buildTeamProjection(
    teamNumber: number,
    teamByNumber: Map<number, AggregatedTeamStats>,
    scoutingEntries: MatchScouting[],
    pitDataByTeam: Record<number, PitScouting | null>,
): { projection: TeamProjection; row: BriefingTeamRow } {
    const team = teamByNumber.get(teamNumber);
    if (!team) {
        const blank: TeamProjection = {
            teamNumber,
            projectedPoints: 0,
            breakdown: { auto: 0, teleop: 0, endgame: 0 },
            confidence: 0.1,
            reliability: "low",
            redFlags: ["Equipo sin datos aggregados"],
        };
        return {
            projection: blank,
            row: {
                teamNumber,
                teamName: `Team ${teamNumber}`,
                projectedPoints: 0,
                breakdownAuto: 0,
                breakdownTeleop: 0,
                breakdownEndgame: 0,
                averageRS: 0,
                averageNP: 0,
                reliability: "low",
                redFlags: ["Sin datos"],
                recentNotes: [],
            },
        };
    }

    const teamScouting = scoutingEntries.filter(e => e.teamNumber === teamNumber);
    const projection = calculateTeamProjection(team, teamScouting, pitDataByTeam[teamNumber] ?? null);

    const recentNotes = teamScouting
        .filter(e => e.notes && e.notes.trim().length > 0)
        .sort((a, b) => (b.timestamp?.seconds ?? 0) - (a.timestamp?.seconds ?? 0))
        .slice(0, 2)
        .map(e => e.notes);

    return {
        projection,
        row: {
            teamNumber,
            teamName: team.teamName,
            projectedPoints: projection.projectedPoints,
            breakdownAuto: projection.breakdown.auto,
            breakdownTeleop: projection.breakdown.teleop,
            breakdownEndgame: projection.breakdown.endgame,
            averageRS: team.averageRS ?? 0,
            averageNP: team.averageNP ?? 0,
            reliability: projection.reliability,
            redFlags: projection.redFlags,
            recentNotes,
        },
    };
}

/**
 * Generates 2-4 bullet points the drive coach can actually act on in-match.
 * These are derived rules, not ML — but they're written so a strategy lead
 * who reads them aloud during pre-match huddle has concrete decisions.
 */
function deriveStrategicFocus(
    prediction: MatchProjection,
    red: BriefingTeamRow[],
    blue: BriefingTeamRow[],
): string[] {
    const focus: string[] = [];

    const redAuto = red.reduce((a, b) => a + b.breakdownAuto, 0);
    const blueAuto = blue.reduce((a, b) => a + b.breakdownAuto, 0);
    const redTele = red.reduce((a, b) => a + b.breakdownTeleop, 0);
    const blueTele = blue.reduce((a, b) => a + b.breakdownTeleop, 0);
    const redEnd = red.reduce((a, b) => a + b.breakdownEndgame, 0);
    const blueEnd = blue.reduce((a, b) => a + b.breakdownEndgame, 0);

    // Auto advantage — recommend doubling down or playing catch-up.
    if (redAuto > blueAuto * 1.25) {
        focus.push("AUTO: ventaja roja. Protejer las posiciones de scoring del aliado durante auto.");
    } else if (blueAuto > redAuto * 1.25) {
        focus.push("AUTO: desventaja en auto. Considerar interrumpir la trayectoria azul desde el inicio del teleop.");
    }

    // Endgame contention
    if (Math.abs(redEnd - blueEnd) < 5 && (redEnd + blueEnd) > 10) {
        focus.push("ENDGAME: ambas alianzas tienen capacidad similar de climb. Decidir orden de subida 30s antes del fin para ganar 20pts dual-parking.");
    }

    // Win prob extremes
    if (prediction.winProbability > 0.75) {
        focus.push("Favoritos claros. Prioridad: asegurar RPs en lugar de score máximo.");
    } else if (prediction.winProbability < 0.25) {
        focus.push("Underdog. Buscar plays de alto-riesgo/alta-recompensa. Defensa agresiva sobre top scorer del oponente.");
    }

    // Red flags from opposing alliance
    const blueFlags = blue.flatMap(t => t.redFlags);
    if (blueFlags.length > 0) {
        focus.push(`Aprovechar debilidades del oponente: ${blueFlags.join(", ")}.`);
    }

    // Conservative defaults if nothing fired
    if (focus.length === 0) {
        focus.push("Match equilibrado. Ejecutar plan estándar; ajustar tras el primer minuto.");
    }

    return focus;
}
