/**
 * Event selector — "¿dónde me conviene competir?"
 *
 * Pure projection logic over historical event field profiles generated by
 * scripts/oracle-backtest.mjs (`profiles` + `export-profiles`, decisions.md
 * #57-#58). Given a team's projected OPR and an event's historical field
 * (OPR mean/σ of teams, event score noise σ), it estimates:
 *
 *  - the team's percentile and expected seed in that field (normal
 *    approximation over the field's OPR distribution),
 *  - alliance-formation verdict (captain / pick / bubble / out) using the
 *    seed thresholds validated in the FPEMX and counterfactual analyses
 *    (decisions.md #58: "pickable" ≈ top 2×alliances for 2-robot formats),
 *  - a strategy note derived from the field's volatility: low-σ fields favor
 *    favorites (results respect OPR), high-σ fields favor challengers
 *    (upsets are live) — the σ-based decision rule from decisions.md #57.
 *
 * All values are directional estimates from HISTORICAL data — the UI must
 * label them as such, never as guarantees (same honesty contract as the
 * Oracle's calibrated probabilities).
 */

export interface EventProfile {
    season: number;
    code: string;
    name: string;
    type: string;
    region: string | null;
    teams: number;
    oprMean: number;
    oprSd: number;
    oprTop: number;
    /** Event score-noise σ_diff (√2·RMS of qual residuals). */
    sigma: number;
}

export type Verdict = "capitan" | "pick" | "burbuja" | "fuera";

export interface EventProjection {
    percentile: number;      // 0-100, share of the field below the team
    expectedSeed: number;    // 1-based
    alliances: number;       // estimated alliance count for the field size
    verdict: Verdict;
    /** Volatility class of the field, drives the strategy note. */
    volatility: "ordenado" | "medio" | "caotico";
}

/** Φ via Abramowitz-Stegun erf — same approximation used across the app. */
function phi(z: number): number {
    const x = z / Math.SQRT2;
    const s = x < 0 ? -1 : 1;
    const a = Math.abs(x);
    const t = 1 / (1 + 0.3275911 * a);
    const y = 1 - ((((1.061405429 * t - 1.453152027) * t + 1.421413741) * t - 0.284496736) * t + 0.254829592) * t * Math.exp(-a * a);
    return 0.5 * (1 + s * y);
}

/**
 * Estimated alliance count from field size. FTC standard brackets are 4/6/8
 * alliances; small events run 4, Premier-scale ~6, Worlds-scale 8.
 */
export function estimateAlliances(teams: number): number {
    if (teams >= 48) return 8;
    if (teams >= 28) return 6;
    return 4;
}

export function projectAtEvent(myOPR: number, p: EventProfile): EventProjection {
    // Normal approximation of the field's OPR distribution. σ floor avoids
    // division blowups on degenerate tiny fields.
    const sd = Math.max(p.oprSd, 1);
    const percentile = phi((myOPR - p.oprMean) / sd) * 100;
    const expectedSeed = Math.min(p.teams, Math.max(1, Math.round(p.teams * (1 - percentile / 100)) + 1));
    const alliances = estimateAlliances(p.teams);

    // Seed thresholds (decisions.md #58): captain ≈ top `alliances`; pickable
    // ≈ top 2×alliances; bubble ≈ top 2.5×alliances.
    let verdict: Verdict;
    if (expectedSeed <= alliances) verdict = "capitan";
    else if (expectedSeed <= 2 * alliances) verdict = "pick";
    else if (expectedSeed <= 2.5 * alliances) verdict = "burbuja";
    else verdict = "fuera";

    // Volatility classes calibrated on the 2024-25 Premier spread observed in
    // the global backtest (σ 33-92): ≤40 ordered, ≥60 chaotic.
    const volatility = p.sigma <= 40 ? "ordenado" : p.sigma >= 60 ? "caotico" : "medio";

    return { percentile, expectedSeed, alliances, verdict, volatility };
}

/**
 * Translation key for the strategy note combining verdict × volatility (σ
 * decision rule, #57). No params needed — every variant is a fixed sentence —
 * so unlike DraftBasis this is a plain key union rather than key+params
 * objects. The UI renders it via next-intl (namespace "EventSelector.strategy"),
 * same rule as every other lib/ module that used to return Spanish sentences:
 * the analysis layer returns a KEY, never prose. See docs/architecture/i18n.md.
 */
export type StrategyKey =
    | "topOrdered"
    | "topChaotic"
    | "topTypical"
    | "bubbleChaotic"
    | "bubbleTypical"
    | "outChaoticUpside"
    | "outAboveLevel";

/** Strategy note key combining verdict × volatility (σ decision rule, #57). */
export function strategyNote(proj: EventProjection): StrategyKey {
    const { verdict, volatility } = proj;
    if (verdict === "capitan" || verdict === "pick") {
        if (volatility === "ordenado") return "topOrdered";
        if (volatility === "caotico") return "topChaotic";
        return "topTypical";
    }
    if (verdict === "burbuja") {
        if (volatility === "caotico") return "bubbleChaotic";
        return "bubbleTypical";
    }
    if (volatility === "caotico") return "outChaoticUpside";
    return "outAboveLevel";
}
