/**
 * Growth curves — how a program's standing evolves from its rookie season on.
 *
 * Generated by `scripts/growth-curves.mjs` from FTCScout's public API, then
 * curated here so the report page ships no fetch. Regenerate with:
 *   node scripts/growth-curves.mjs MX
 *
 * WHY PERCENTILES AND NOT OPR. OPR is not comparable across seasons — every
 * FTC game scores differently, so a 50 in Power Play and a 50 in DECODE mean
 * nothing alike. Each team is ranked within its own (season, region) cohort
 * first. That is comparable across seasons, and it is the more useful question
 * anyway: what matters competitively is whether you are climbing relative to
 * the teams you actually face.
 *
 * WHY TWO CURVES. The naive curve mixes two different things: programs getting
 * better, and weak programs folding. `all` includes everyone, so its tail is
 * survivor-biased and reads optimistically. `cohort` follows only the 20
 * Mexican programs observed for five or more seasons — nobody leaves mid-curve,
 * so whatever climb remains there is real improvement rather than attrition.
 * The two together are the honest picture; either alone is misleading.
 */

export interface GrowthPoint {
    /** 1 = rookie season. */
    year: number;
    /** Teams contributing to this point — watch it shrink; that IS the attrition. */
    teams: number;
    p25: number;
    median: number;
    p75: number;
}

export const MX_GROWTH = {
    region: "MX",
    regionLabel: "México",
    /** Teams in the region with a known rookie year. */
    teamsTotal: 189,
    /** Teams in the fixed 5+ season cohort. */
    cohortSize: 20,

    /** Every team, every season observed. Tail is survivor-biased. */
    all: [
        { year: 1, teams: 140, p25: 16.8, median: 33.8, p75: 57.6 },
        { year: 2, teams: 86, p25: 25.3, median: 52.7, p75: 71.9 },
        { year: 3, teams: 54, p25: 26.3, median: 48.1, p75: 66.5 },
        { year: 4, teams: 31, p25: 37.7, median: 54.6, p75: 75.5 },
        { year: 5, teams: 17, p25: 43.4, median: 59.3, p75: 84.3 },
        { year: 6, teams: 18, p25: 42.9, median: 80.4, p75: 92.5 },
        { year: 7, teams: 19, p25: 65.4, median: 87.5, p75: 94.8 },
    ] as GrowthPoint[],

    /** Fixed cohort: only programs with 5+ observed seasons. */
    cohort: [
        { year: 1, teams: 4, p25: 28.7, median: 43.8, p75: 58.3 },
        { year: 2, teams: 6, p25: 25, median: 35.4, p75: 47.6 },
        { year: 3, teams: 11, p25: 27, median: 50, p75: 61.3 },
        { year: 4, teams: 14, p25: 46, median: 65.5, p75: 75.7 },
        { year: 5, teams: 17, p25: 43.4, median: 59.3, p75: 84.3 },
        { year: 6, teams: 16, p25: 44.6, median: 80.4, p75: 93.5 },
        { year: 7, teams: 14, p25: 79.4, median: 89.6, p75: 96.5 },
    ] as GrowthPoint[],

    /**
     * Iron Lion's own standing, computed the same way against the 131 Mexican
     * teams with 2025 data (OPR 63.4 → 28th of 131).
     */
    self: { year: 1, percentile: 79.2, rank: 28, of: 131 },

    /**
     * The window is 2019-2025, so a program that started before 2019 only
     * appears from its later seasons on. That thins the fixed cohort's early
     * years (season 1 rests on 4 teams) — the shape there is indicative, not
     * settled. The all-teams curve is well powered through season 4.
     *
     * No prose here — windowStart/windowEnd are params for the "GrowthCurves.
     * caveat" translation key (docs/architecture/i18n.md); the UI supplies the
     * sentence per locale.
     */
    caveatWindowStart: 2019,
    caveatWindowEnd: 2025,
} as const;
